export interface Patient {
    LastName: string,
    FirstName: string,
    MiddleName: string,
    Extension?: string,
    Address: string,
    Region: string,
    Occupation: string,
    BirthDate: string,
    Age: number,
    ContactNumber: string,
    Branch: string,
    DateAdmitted: string,
    TimeAdmitted: string,
    DateDischarged: string,
    TimeOfDischarged: string,
    DateOfBirth: string,
    TimeOfBirth?: string,
    Image?: string,
    PhilHealthId?: string,
}